fragment CharCardFields on Character {
  id
  name
  species
  status
  image
  episode {
    name
  }
  location {
    name
  }
}

query Character($id: ID!) {
  character(id: $id) {
    ...CharCardFields
    type
    gender
    origin {
      name
    }
    episode {
      id
      air_date
      episode
    }
  }
}

query Characters($page: Int, $filter: FilterCharacter) {
  characters(page: $page, filter: $filter) {
    info {
      pages
      next
      prev
    }
    results {
      ...CharCardFields
    }
  }
}

query CharactersByIds($ids: [ID!]!) {
  charactersByIds(ids: $ids) {
    ...CharCardFields
  }
}
